server:
  port: 8001

logging:
  level:
    root: warn
    com.ilirus.oauth: debug

spring:
  application:
    name: irs-server-resource
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true