server:
  port: 80

logging:
  level:
    root: warn
    com.ilirus.oauth: debug

spring:
  application:
    name: order-server
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  resources:
    static-locations: classpath:/static/